### ISSUE TITLE
Possible fringe color issues with Emacs 26

### ISSUE THREAD

**Issue by drot** [purcell/color-theme-sanityinc-tomorrow#100]
Testing out the new Emacs 26 pretest (though I haven't tested this with the current stable Emacs 25.3) I found that if I start it in daemon mode the fringe colors are incorrect like this:

![fringe](https://user-images.githubusercontent.com/85483/31553205-f6872822-b039-11e7-98c8-1adc481249dc.png)

Reloading the theme fixes the issue. So maybe we should explicitly set the colors instead of relying on the function to set `low-contrast-bg`?

**Comment by purcell** [comment]
Why do you think the function is the problem?

**Comment by purcell** [comment]
P.S. I'm using a recent 26.x series build and I don't see this issue.

**Comment by drot** [comment]
Just to be clear this is what I'm seeing upon running `emacsclient -c` in a terminal to spawn a graphical frame, or using the new systemd unit that Emacs 26 now provides. And this what `describe-face` shows:

![2017-10-14-100935_628x516_scrot](https://user-images.githubusercontent.com/85483/31574126-4811fb92-b0c9-11e7-996c-9d86c343a53c.png)

Though why you cannot reproduce the issue left me wondering that maybe this is a GTK issue.

**Comment by purcell** [comment]
> Though why you cannot reproduce the issue left me wondering that maybe this is a GTK issue.

That's my guess. I'm on MacOS. I haven't tested this with daemon mode, to be fair, but I can't see why that would make a difference.

**Comment by Postroutine** [comment]
Same problem with Emacs client 25.3

**Comment by purcell** [comment]
> Reloading the theme fixes the issue. So maybe we should explicitly set the colors instead of relying on the function to set low-contrast-bg?

Does doing this actually help for you, @drot? Are you implying that you think the functions in `color.el` don't work properly in certain cases?

**Comment by drot** [comment]
Yeah, if the daemon is running and I spawn a graphical frame I have to
reload the theme to get proper fringe colors.

**Comment by purcell** [comment]
> Yeah, if the daemon is running and I spawn a graphical frame I have to reload the theme to get proper fringe colors.

I mean to say: if you change the theme code so that the colors are explicitly set rather than computed by the function, do things work properly?

**Comment by drot** [comment]
Yes if I change the fringe color explicitly (using the `sanityinc-tomorrow-night` theme for example):

`(fringe (:background "#228024802780" :foreground ,comment))`

This works with the daemon initialization.

**Comment by drot** [comment]
After some further testing the background color also isn't specified when running with `emacs -nw`

![fringe](https://user-images.githubusercontent.com/85483/35799832-54bbd1fe-0a67-11e8-9106-a3434bd23741.png)

This is also fixed by specifying the color manually.
