### ISSUE TITLE
ansi-color black and white names are switched in call to setq ansi-color-names-vector

### ISSUE THREAD

**Issue by Hamzehn** [purcell/color-theme-sanityinc-tomorrow#101]
Hi,

First, thank you for the immensely valuable resources you are making available to Emacs users.

I recently started using your .emacs.d configuration, and noticed that when I open a shell buffer what is supposed to appear as white text actually appears as dark test with #424242 while what is supposed to be black text appears with color #eaeaea.

I believe the source of this comes down to this line in color-theme-sanityinc-tomorrow.el, where the ansi-color-names-vector is set.

https://github.com/purcell/color-theme-sanityinc-tomorrow/blob/a07c940b5e73ed67ff1e13f584065af7b577ec00/color-theme-sanityinc-tomorrow.el#L1244

The first element in the ansi-color-names-vector should correspond to ansi color black, while the last should correspond to ansi color white. However, the current code uses foreground (#eaeaea) for black and bg-contrast (#424242) for white. Shouldn't they be switched?

I tried switching them so that the line becomes:

`         (ansi-color-names-vector (vector ,contrast-bg ,red ,green ,yellow ,blue ,purple ,aqua ,foreground))`

And now the issue goes away.

**Comment by purcell** [comment]
The idea is that when the ANSI standard colour is "WHITE", that assumes a black background. So ANSI's "white" should be translated to the foreground colour, for maximum contrast. If you use a dark theme, then "WHITE" should be a light colour, and if you use a light theme, it should be a dark colour. Is that the behaviour you are seeing?

**Comment by Hamzehn** [comment]
I thought it may have been about that, but it seems that the "light" and "dark" themes already handle switching foreground/background colors between dark/light themes just fine without the need to do this switch in the ansi-color-names-vector. Here are screenshots of what I see inside the shell buffer in both dark and light themes when I list the ~/.emacs.d/elpa-25.1/ directory:

Under the default "dark" theme:
![image](https://user-images.githubusercontent.com/27373978/32985263-ad34feae-ccbf-11e7-8c28-4da94e17111e.png)

If switch to the "light" theme with M-x light and restart the shell:
![image](https://user-images.githubusercontent.com/27373978/32985264-b31b31e4-ccbf-11e7-8b71-63e07640738e.png)

I'll post the behavior I see when I make the change I mentioned in my original post.

**Comment by Hamzehn** [comment]
Here is the behavior I see when I change line 1244 to:

``(ansi-color-names-vector (vector ,contrast-bg ,red ,green ,yellow ,blue ,purple ,aqua ,foreground))`

I'm using GNU Emacs 25.1.1 (x86_64-w64-mingw32) on Windows 10.

Under the default "dark" theme:
![image](https://user-images.githubusercontent.com/27373978/32985336-4f914d78-ccc1-11e7-958e-a88943021004.png)

Under the "light" theme:
![image](https://user-images.githubusercontent.com/27373978/32985339-59624d84-ccc1-11e7-980f-2c0473586b90.png)

**Comment by purcell** [comment]
Thanks for the screenshot, and for your help with this - I've patched the theme accordingly.
