### ISSUE TITLE
Failed to enable theme: sanityinc-tomorrow-night

### ISSUE THREAD

**Issue by mambolevis** [purcell/color-theme-sanityinc-tomorrow#106]
Hi,

The following message is shown despite of the fact that the package is correctly loaded.
 
`Failed to enable theme: sanityinc-tomorrow-night`

![image](https://user-images.githubusercontent.com/13024208/36916250-b05b555c-1e53-11e8-86cb-74ab5f98b71d.png)

**Comment by purcell** [comment]
I can't reproduce this, sorry, and I don't use `use-package`. Which Emacs version are you using?

**Comment by mambolevis** [comment]
GNU Emacs 26.0.91 (build 1, x86_64-w64-mingw32) of 2018-03-02

> I can't reproduce this, sorry, and I don't use use-package

If you could send me your setup, I would comment use package and test your version.

**Comment by purcell** [comment]
For the most part, I just install the package and use `M-x customize-themes`, but calling `color-theme-sanityinc-tomorrow-night` also works fine for me.

I have some [related config](https://github.com/purcell/emacs.d/blob/master/lisp/init-themes.el), but I don't think it's relevant to the issue you're seeing: I suspect that the problem is the order of when this code is called relative to any saved customization. Maybe check the saved customization code to see if it is also trying to set the themes. With a startup file containing only the following, everything should work, assuming you've already installed the package:
```el
(package-initialize)
(color-theme-sanityinc-tomorrow-night)
```

**Comment by mambolevis** [comment]
> I suspect that the problem is the order of when this code is called relative to any saved customization. Maybe check the saved customization code to see if it is also trying to set the themes

Yes, the problem was there. My `custom.el` was called previous to the color-theme package. I change the order and the message disappears. Thanks.

I have a related question: My two favorite color-themes are: and `color-theme-sanityinc-tomorrow` and `zenburn-theme` and I used to interchange them frequently. In order to guarantee no influence from one to the other, I need to keep only one installed. **Now the question**: It is possible to have both installed (from melpa) and just activate one of them and without having interference from the disabled one?

**Comment by purcell** [comment]
> I have a related question: My two favorite color-themes are: and color-theme-sanityinc-tomorrow and zenburn-theme and I used to interchange them frequently. In order to guarantee no influence from one to the other, I need to keep only one installed. Now the question: It is possible to have both installed (from melpa) and just activate one of them and without having interference from the disabled one?

That's a tricky topic, and I've noticed these sorts of isses before, but I don't have a solid solution.

Generally it should be possible to keep both installed, but not loaded: ie. you can have both packages on your system, and use either theme without issues. Sometimes switching between themes can leave remnants of the previous theme active, and I'm not exactly sure why. I note that the custom theme system supports multiple active themes, so I personally like to use `M-x customize-themes`, where you will find an option to allow only one active theme at a time. What makes this complicated is that themes are used not just to set font faces, but also about arbitrary other variables that affect appearance, and I think that these can cause issues.
