### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by demonchild2112** [purcell/color-theme-sanityinc-tomorrow#107]

**Comment by purcell** [comment]
There is already a licence: GPLv3 or greater. It's in the file headers.

**Comment by demonchild2112** [comment]
I probably should have said 'Please add a licence file, for better visibility/explicitness.'

Also, some of the files in this repo do not have a licence header.

**Comment by purcell** [comment]
> Also, some of the files in this repo do not have a licence header.

Makes sense - done in 6be4fea. Thanks!
