### ISSUE TITLE
Wrong highlight face

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/color-theme-sanityinc-tomorrow#108]
Hi,

I am using the latest version of the theme from MELPA, on GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2018-03-20.

This is what happens when using `swiper` in a Clojure file (with `clojure-mode` and `cider` enabled):

![shot](https://user-images.githubusercontent.com/8199224/37659245-c2882ade-2c4f-11e8-8b34-c6c214d71fd6.png)

However, this is `swiper` in an Emacs Lisp file:

![shot1](https://user-images.githubusercontent.com/8199224/37659264-cf59d6c2-2c4f-11e8-9e0d-6488c91aeed0.png)

I'm opening the issue here, but it could be helpful to cc @abo-abo and @bbatsov because I'm not sure which package is causing the problem.

**Comment by manuel-uberti** [comment]
Anything? :)

**Comment by purcell** [comment]
Cause isn't immediately obvious to me, having spent a couple of minutes looking at the face definitions here. I'm not working with Clojure these days, so it's a fiddle for me to reproduce this, and I won't investigate further myself, but happy to merge a fix if you come up with one.

**Comment by manuel-uberti** [comment]
Asking @bbatsov: could it be related to https://github.com/clojure-emacs/clojure-mode/issues/474?

**Comment by abo-abo** [comment]
@manuel-uberti It may be possible to fix it within Ivy code base with a patch to `colir-blend-face-background`.

**Comment by manuel-uberti** [comment]
Thanks @abo-abo. I'll have to understand what `colir-blend-face-background` does, because for what I see in my setup this only happens when using `swiper` with Clojure files.

**Comment by manuel-uberti** [comment]
Resetting `clojure-mode` to [1fdb3cdec1bd0584caadb9c45352caed9ddb76c1](https://github.com/clojure-emacs/clojure-mode/commit/1fdb3cdec1bd0584caadb9c45352caed9ddb76c1) fixed it.

I am going to close this, since there is already an open issue `clojure-mode` ([#474](https://github.com/clojure-emacs/clojure-mode/issues/474))
