### ISSUE TITLE
the face color of hl-line-mode &  selected region is too similar

### ISSUE THREAD

**Issue by xuuexu** [purcell/color-theme-sanityinc-tomorrow#116]
Sir. I like your theme `sanityinc-tomorrow-bright` a lot, for its high contrast.
However, when I open `global-hl-line-mode`, and set mark then select some region, 
the face color between them always made me feel mixed.  
See its result: 
<img width="657" alt="screen shot 2018-08-25 at 14 44 22" src="https://user-images.githubusercontent.com/31076337/44615821-def46a00-a875-11e8-832c-fdb76c1c3dd9.png">
Any plan to make it look more clear?

**Comment by purcell** [comment]
No plans to change this, sorry. There aren't many colours in this theme, so when the region is active (which shouldn't happen all the time), it's acceptable to me that other faces aren't perfect.
