### ISSUE TITLE
Dealing with :extend

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/color-theme-sanityinc-tomorrow#140]
This is not an issue, but a question about a recent change on Emacs `master`.

See: [Emacs 27 update changed how highlighted lines look. How can I fix this?
](https://www.reddit.com/r/emacs/comments/diahh1/emacs_27_update_changed_how_highlighted_lines/)

From `etc/NEWS`:

```
** New face attribute ':extend' to control face extension at EOL.
The new face attribute ':extend' controls whether to use the face for
displaying the empty space beyond end of line (EOL) till the edge of
the window.  By default, this attribute is non-nil only for 'region'
and 'hl-line' faces; any other face that crosses end of line will not
affect the display of the empty space at EOL.
```

As the report on Reddit shows, there are issues on highlights in different places (e.g., Magit faces). It seems to be unrelated to the theme, though, because with `emacs -Q` and the default theme, Magit faces still look weird now. (Again, as reported on Reddit.)

I am sure it will be fixed soon on Emacs `master`, but do you think there is anything that can be done to `color-theme-sanityinc-tomorrow` to accommodate the problematic faces?

I am willing to help, of course. :)

**Comment by manuel-uberti** [comment]
FWIW, it may be enough to just add `:extend t` to `region` and `hl-line` faces for now.

**Comment by drot** [comment]
The theme doesn't touch the `hl-line` face so it already has the `:extend` attribute on by default, only the `region` face needs to be adapted. Pending Emacs bug report: [#37774](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774).

**Comment by manuel-uberti** [comment]
Do you want me to file a PR with `:extend t` added to `region`?

**Comment by manuel-uberti** [comment]
@drot I can't test it with previous Emacs versions, but are we sure older the theme will now work for older Emacsen too?

**Comment by drot** [comment]
Seems to work fine with 26.3 on my machine and all the tests are passing.

**Comment by manuel-uberti** [comment]
Accord to [this](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774#233), other faces that can be fixed with `:extend t` are:

- Magit
```
(with-eval-after-load 'magit
  (dolist (face '(magit-diff-hunk-heading
                  magit-diff-hunk-heading-highlight
                  magit-diff-hunk-heading-selection
                  magit-diff-hunk-region
                  magit-diff-lines-heading
                  magit-diff-lines-boundary
                  magit-diff-conflict-heading
                  magit-diff-added
                  magit-diff-removed
                  magit-diff-our
                  magit-diff-base
                  magit-diff-their
                  magit-diff-context
                  magit-diff-added-highlight
                  magit-diff-removed-highlight
                  magit-diff-our-highlight
                  magit-diff-base-highlight
                  magit-diff-their-highlight
                  magit-diff-context-highlight
                  magit-diff-whitespace-warning
                  magit-diffstat-added
                  magit-diffstat-removed
                  magit-section-heading
                  magit-section-heading-selection
                  magit-section-highlight
                  magit-section-secondary-heading
                  magit-diff-file-heading
                  magit-diff-file-heading-highlight
                  magit-diff-file-heading-selection))
    (set-face-attribute face nil :extend t)))
```

- ediff
```
(dolist (face '(ediff-current-diff-A
                ediff-current-diff-Ancestor
                ediff-current-diff-B
                ediff-current-diff-C
                ediff-even-diff-A
                ediff-even-diff-Ancestor
                ediff-even-diff-B
                ediff-even-diff-C
                ediff-fine-diff-A
                ediff-fine-diff-Ancestor
                ediff-fine-diff-B
                ediff-fine-diff-C
                ediff-odd-diff-A
                ediff-odd-diff-Ancestor
                ediff-odd-diff-B
                ediff-odd-diff-C))
  (set-face-attribute face nil :extend t))
```
I tried this code in my init.el, and it seems to work just fine. Is there anything I can do for this theme?
