### ISSUE TITLE
Following official colour usages?

### ISSUE THREAD

**Issue by ianpan870102** [purcell/color-theme-sanityinc-tomorrow#161]
Hi Steve, thanks for this wonderful port, I have been using the Tomorrow Blue theme for a while now. But earlier today I found some differences in terms of colour usages between your port and the official screenshots. For example, keywords (if/else/return) in sanityinc-tomorrow-blue are highlighted green, while in the official screenshot they're light-purple; another example would be that the official screenshots have numbers highlighted light-orange, but sanityinc-tomorrow-blue has them as light blue. Also, variables should be light-red, but sanityinc-tomorrow-blue uses light-yellow for variables.
Just wanted to point this out to you, in case you haven't noticed.

**Comment by purcell** [comment]
Hey hey - thanks for getting in touch! This is an interesting topic, and one that I have thought about.

Yes, there are some differences in colour, and to _some limited extent_ I have applied the `tomorrow` colours according to my own preferences. However, there are actually no well-defined semantic rules about which colours should represent which types of highlight elements for programming languages, and such rules would be impossible to follow in the general case: highlighting systems vary significantly between editors, and even between languages in the same editor.

For example, Emacs applies some of its standard faces in semantically different ways between Ruby and Lisp, so assigning colours in an Emacs theme is a matter of finding a balance which gives enough variety of colours while achieving consistency where possible. Finding a reasonable assignment of the standard colours in this theme was quite tricky, and there may be cases where some assignments could be changed to more closely resemble the official screenshots of vim/Sublime/whatever it is, but then other things would look worse. I initially tried to follow the upstream screenshots, and this is where we ended up. :-)
