### ISSUE TITLE
load-theme has no effect

### ISSUE THREAD

**Issue by martenlienen** [purcell/color-theme-sanityinc-tomorrow#170]
I just pulled the latest version with straight and now `(load-theme 'sanityinc-tomorrow-day t)` has no longer any effect. `M-x color-theme-sanityinc-tomorrow-day` seems to load a few colors but not all of them. Other themes, e.g. nord-theme, still work as usual.

**Comment by purcell** [comment]
Hmm, thanks, I may have been too hasty merging https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/169, but I'm not sure why that would break anything. I'll investigate now.

**Comment by purcell** [comment]
Should be fixed now — thanks for the heads-up.

**Comment by martenlienen** [comment]
Works again, thanks for the quick fix!
