### ISSUE TITLE
ediff colors using a very stark background

### ISSUE THREAD

**Issue by dakrone** [purcell/color-theme-sanityinc-tomorrow#25]
I think the ediff colors might be able to be improved a bit (especially the background):

![2015-07-29-145054_1440x900_scrot](https://cloud.githubusercontent.com/assets/19060/8969555/7f0036ae-3601-11e5-96cf-f58d023d05f8.png)

I'm happy to work on a PR if you agree, but it might be quite a while so feel free to change this if I don't get to it any time soon :)

**Comment by purcell** [comment]
Thanks. Looks like a couple of face definitions are missing rather than wrong...

**Comment by dakrone** [comment]
Here's another change, the green used for changes can almost entirely wash out the text and make it hard to read the actual code that was added:

![screenshot from 2015-11-06 15-32-56](https://cloud.githubusercontent.com/assets/19060/11010411/c5a7f9fa-849b-11e5-9874-c030aaae900a.png)

**Comment by purcell** [comment]
Yeah, doesn't look so great! Not sure I'll get around to fixing this in a hurry, so perhaps a PR would be an option?
