### ISSUE TITLE
Cannot load automatically

### ISSUE THREAD

**Issue by panagiotious** [purcell/color-theme-sanityinc-tomorrow#31]
Hello,

I am having trouble setting up `tomorrow` to automatically load. Although I have installed it through `marmalade` and when I do `M-x color-theme-sanityinc-tomorrow-night` or `M-x load-theme [RET] sanityinc-tomorrow-night [RET]` it works perfectly, if I try any way to get it in my `.emacs` file, it simply doesn't like it! I have managed to get other themes to work, but this one simply breaks. I am completely new to Emacs, but have spent several hours on this!

My setup is Mac OS 10.11.3, with GNU Emacs 24.5.1 and have also tried on Debian Wheezy and Jessie. My `.emacs` file contains:

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (sanityinc-tomorrow-night)))
 '(custom-safe-themes
   (quote
    ("06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" default)))
 '(package-archives
   (quote
    (("marmalade" . "http://marmalade-repo.org/packages/")
     ("gnu" . "http://elpa.gnu.org/packages/")))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'color-theme-sanityinc-tomorrow)
;; (load-theme 'color-theme-sanityinc-tomorrow-night t)
```

and the debug output is

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "color-theme-sanityinc-tomorrow")
  require(color-theme-sanityinc-tomorrow)
  eval-buffer(#<buffer  *load*> nil "/Users/panagiotious/.emacs" nil t)  ; Reading at buffer position 938
  load-with-code-conversion("/Users/panagiotious/.emacs" "/Users/panagiotious/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\ [...]
  command-line()
  normal-top-level()
```

**Comment by purcell** [comment]
`(require 'color-theme-sanityinc-tomorrow)` should not be necessary, and `(load-theme 'color-theme-sanityinc-tomorrow-night t)` should be `(load-theme 'sanityinc-tomorrow-night t)`.

Since you've installed the theme using the package system, you're probably forgetting to call `package-initialize` before trying to `require` and load it.

**Comment by panagiotious** [comment]
Oh come on! So simple.. Thank you! I will try to change your readme file a little bit to include this for new users and submit a PR!

Thank you so much,

Panagiotis

**Comment by purcell** [comment]
:+1:
