### ISSUE TITLE
flycheck icons are not visible

### ISSUE THREAD

**Issue by jbpotonnier** [purcell/color-theme-sanityinc-tomorrow#35]
When using this theme, flycheck icons are not visible.
Maybe it is caused by this setting, using the same color as background and foreground.

    (flycheck-fringe-error (:foreground ,red :background ,red))
    (flycheck-fringe-info (:foreground ,aqua :background ,aqua))
    (flycheck-fringe-warning (:foreground ,orange :background ,orange))

Icons are useful for me because I'm using [`dgutov/diff-hl`](https://github.com/dgutov/diff-hl) and it is visually conflicting sometimes

**Comment by purcell** [comment]
Thanks. Should be better now.

**Comment by jbpotonnier** [comment]
Yes it is!
Thanks

**Comment by purcell** [comment]
Also: I noticed that the flycheck fringe icons seem to get set with the colors from the theme that was in effect at the time flycheck is loaded, which is a bit quirky, and led to confusion in the past when I'd tested this.
