### ISSUE TITLE
Gutter colors

### ISSUE THREAD

**Issue by theherk** [purcell/color-theme-sanityinc-tomorrow#36]
The gutter is the same color as the background. It would be great to have it be slightly different so it doesn't look like extra code spaces, like many other themes.

Also, this seems to be the only theme that highlights a block in flycheck with an empty circle rather than a colored circle.

It looks like [this in Tomorrow themes](http://imgur.com/p5IBeK7).

It looks like [this in Material](https://imgur.com/3z8nMw3).

It looks like [this in Zenburn](http://imgur.com/s1tjwJ4) (which has the contrasted gutter, too).

**Comment by purcell** [comment]
> The gutter is the same color as the background. It would be great to have it be slightly different so it doesn't look like extra code spaces, like many other themes.

Is that the gutter or the fringe?

The fringe was a different colour to the background until very recently, and I'm experimenting with this new look right now. Not sure if I'll keep it. I don't really want to make the behaviour customisable, though.

> Also, this seems to be the only theme that highlights a block in flycheck with an empty circle rather than a colored circle.

Are those screenshots taken in a terminal? For me, the flycheck fringe items have a red block background.

**Comment by theherk** [comment]
I guess I meant the fringe. I don't actually know the difference.

Those screenshots are taken in the gui. They do have the block background, unless I am confused. Is that how it should be. How it is pictured. It seems all the other themes I check have the colored circle.

**Comment by purcell** [comment]
Yes, that was intentional, though I might change it.

**Comment by purcell** [comment]
I changed the flycheck fringe faces in 5ce58a5aaa177fee7210284f94913ba71d009009. :-)

**Comment by theherk** [comment]
Looks great, btw. Thank you.
