### ISSUE TITLE
No definitions for helm-ff-dotted-directory and helm-ff-dotted-symlink-directory

### ISSUE THREAD

**Issue by Fanael** [purcell/color-theme-sanityinc-tomorrow#38]
The result is pretty ugly:

![ugh](https://cloud.githubusercontent.com/assets/270470/16554586/2746fc00-41d0-11e6-8a05-e619ca81e701.png)

**Comment by purcell** [comment]
True. Do you have a suggestion? Maybe something that fits in with the dired faces?

**Comment by Fanael** [comment]
I'd just make them same as `helm-ff-directory` and `helm-ff-symlink` respectively.

**Comment by Fanael** [comment]
Thanks!
