### ISSUE TITLE
[Suggestion] Slightly different background between active/inactive windows

### ISSUE THREAD

**Issue by ludwigpacifici** [purcell/color-theme-sanityinc-tomorrow#44]
Hello @purcell 

Do you think it is a good idea to have a slightly different background color between the window which has the focus and other windows (in the case I splitted windows)?

The purpose is to help to see which window has the focus.

**Comment by purcell** [comment]
The modeline colours are already different for this purpose. In general, there aren't enough background colours available in the standard palette for these themes to make your suggestion work, and I'm wary of introducing further colours.

But more practically, there is no specific face used by Emacs for focused vs. unfocused windows, so the theme would need extra code (which would only work in the very latest Emacs versions) to do some nasty per-magic face remapping, and I _really_ don't want to get into that! :-)

**Comment by ludwigpacifici** [comment]
Thanks for the explanations. Keep up your good work :-)
