### ISSUE TITLE
How to change background coloring in terminal using this theme?

### ISSUE THREAD

**Issue by sdban** [purcell/color-theme-sanityinc-tomorrow#45]
Is there a way to ensure transparent background in this theme when emacs is running in a terminal (with <code> -nw </code> ) option?

In a different theme I was able to do it by setting <code> background-color nil </code>. But I cannot seem to find that option here. 

Thanks!

**Comment by purcell** [comment]
Nope, there’s no mechanism for this right now, because generally it’s going to lead to issues. Can you explain the reasoning, please? Why would you want to have to configure and synchronise colours in both your terminal and Emacs?

**Comment by sdban** [comment]
In terminal the main issue I have is that :  Color themes do not seem to offer terminal transparency. The default emacs theme does it....and I have found very little documentation about how one might do it. 
By setting the alpha I can easily get transparency in the gui so that this not a problem. 
I am a little confused why that is the case. 

I come from  a vim background so the terminal is a natural choice. My work-flow and habits have evolved around using a guake type transparent terminal. I am still not at a stage where I can live within emacs  multiple terminal tabs are useful to me.   


The second reason is that  even though color schemes are great sometimes it helps to override some colors...say I would like to have better contrast on comments in a heavily commented document. 

In this case it seems that an ability to override the color-schemes will be very helpful. In vim this is not very hard to do...and I thought may be something similar works for emacs. 

There are times when I need to do edit files remotely. Then emacs  terminal is indispensable.

**Comment by purcell** [comment]
I don't think that terminal Emacs supports colours that are transparent -- usually the terminal just provides the ability to make all its contents transparent. I assumed you were talking about disabling the background colour in the theme.

As far as overriding themes, there's a built-in mechanism for this: Emacs supports having multiple active color themes, so you can define your own theme which just specifies a few faces, and enable that at the same time as a different theme, such as mine. (You can see the option for multiple active themes in `M-x customize-themes`.)
