### ISSUE TITLE
Is border for mode-line enabled by default? 

### ISSUE THREAD

**Issue by 1-9** [purcell/color-theme-sanityinc-tomorrow#46]
I see a border around the mode-line in sample images provided on melpa, however I don't see it in my theme. Is there anything I should do to get the border around the mode-line. I am on emacs 25 and this is how my mode-line looks like.

<img width="1017" alt="screen shot 2017-01-08 at 11 04 59 pm" src="https://cloud.githubusercontent.com/assets/5510191/21757038/f5da4c9c-d5f6-11e6-9bbc-23b25f663bd3.png">

**Comment by purcell** [comment]
That's how it looks for me, too, so the sample images must be outdated. There used to be a border, but I dropped it at some point. I may yet bring it back.

**Comment by 1-9** [comment]
+1 border please, it differentiates well with the buffer contents.
