### ISSUE TITLE
Hope to set color theme's default keyword font style be 'bold'

### ISSUE THREAD

**Issue by lvii** [purcell/color-theme-sanityinc-tomorrow#48]
Hi,

 sanityinc-tomorrow color theme default **NOT** set keyword font style be **bold**,

When I switch to `sanityinc-tomorrow-light` theme from `wombat`,  
`wombat` theme's font sytle still keeped **bold**, the screenshot was below : 

![bold_font](https://cloud.githubusercontent.com/assets/309721/24035228/a1d0cd10-0b2f-11e7-9775-e49b0770b5c9.png)

**Comment by purcell** [comment]
This isn't an issue with this theme: you probably have both themes enabled. Try using `M-x customize-themes` to select only the Tomorrow theme. There's an option there to allow or disallow enabling multiple themes simultaneously: ensure that is turned off.
