### ISSUE TITLE
`magit-diff-context` face looks really weird in latest elpa version (bright theme)

### ISSUE THREAD

**Issue by jguenther** [purcell/color-theme-sanityinc-tomorrow#67]
e.g.:

![image](https://cloud.githubusercontent.com/assets/179915/26082278/57e45fba-398c-11e7-9ab5-968237f89874.png)

It didn't used to have the grey highlight background colour on unchanged/context lines. Looking through the code, `magit-diff-context` is defined with `:foreground ,background` [here](https://github.com/purcell/color-theme-sanityinc-tomorrow/blob/0811060/color-theme-sanityinc-tomorrow.el#L452), which from `describe-face` seems to be the one that looks odd.

Total stab in the dark, but is there some reason to use the `background` arg as `:foreground` or is that a typo? Sorry not very familiar with theming.

**Comment by purcell** [comment]
Thanks for spotting this. @drot - do you have an idea of how to address this? I think it's related to your recent revamping of the `magit` faces?

**Comment by drot** [comment]
Sure if it's too harsh we can just change it to `:foreground ,comment` like this:
![region](https://cloud.githubusercontent.com/assets/85483/26148000/8c44dff4-3af5-11e7-9719-50d80f2cc1a5.png)

**Comment by purcell** [comment]
Thanks, yes: I like that fix. What do you think, @jguenther ?

**Comment by jguenther** [comment]
Looks good.

I also noticed that if `magit-diff-refine-hunk` is enabled, the `diff-refine-added` face makes refined text invisible. I think it's because it inherits `diff-added` with `inverse-video`, but `magit-diff-removed` is the non-refined face in `magit-diff` buffers.

```lisp
      (diff-added (:foreground ,green))
      (diff-removed (:foreground ,orange))
      ;; ...
      (diff-refine-added (:inherit diff-added :inverse-video t))
      (diff-refine-removed (:inherit diff-removed :inverse-video t))
```

**Comment by drot** [comment]
Yeah that's pretty nasty, so I added `blue` for added and `orange` for removed.

Before:
![region](https://cloud.githubusercontent.com/assets/85483/26161492/5a29ed32-3b24-11e7-8473-236030db189f.png)

After:
![region2](https://cloud.githubusercontent.com/assets/85483/26161808/411d53c8-3b25-11e7-9fca-98a8e112381e.png)

**Comment by bhollis** [comment]
I've also noticed that the selected hunk gets bolded - can that also be removed?

**Comment by purcell** [comment]
Fixed now - thanks for filing this.
