### ISSUE TITLE
Tooltip font color is too dark too see after addition of the tooltip background face

### ISSUE THREAD

**Issue by Nelthorim** [purcell/color-theme-sanityinc-tomorrow#74]
After the tooltip background face was added, font is still the same colour as before and becomes almost unreadable. In case it matters, I'm currently on Windows.

![image](https://cloud.githubusercontent.com/assets/2954157/26248228/52e3b9e2-3c99-11e7-8845-d9a697abf526.png)

**Comment by drot** [comment]
Can you check if it happens if the foreground is defined? Currently it's defined as:
`(tooltip (:background ,highlight))`
Try to see if the problem persists with:
`(tooltip (:foreground ,foreground :background ,highlight))`

**Comment by Nelthorim** [comment]
When the foreground is defined, the font looks proper.

![image](https://cloud.githubusercontent.com/assets/2954157/26250355/a705c35a-3ca1-11e7-9d19-61038809c911.png)

**Comment by purcell** [comment]
I committed a fix for this - let me know how it works out, please. You'll have to wait for MELPA to build a fresh package.

**Comment by Nelthorim** [comment]
Fix worked (yellow color, but I'll accept it as a design choice, as it's probably more readable than the white 😄)
