### ISSUE TITLE
AUCTeX's font-latex-*-face doesn't seem to be  covered yet

### ISSUE THREAD

**Issue by IMFTC** [purcell/color-theme-sanityinc-tomorrow#84]
After installing AUCTeX I noticed that LaTeX mode uses some garish faces coming from AUCTeX's font-latex.el, which seems to introduce more faces, not yet covered by sanityinc-tomorrow. Would be nice to have these covered. So this is not a bug but a feature request ;)

**Comment by purcell** [comment]
Thanks. I don't use LaTeX at all, so I'm not in a position to patch this myself, but if you'd like to send a pull request I'd be happy to consider it.

**Comment by IMFTC** [comment]
Looks like https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/e7f5d175916df20c411713e49be8b58aac36f7ed has covered this for the most (or all?) parts.

**Comment by drot** [comment]
Yep, I guess we can close this now.
