### ISSUE TITLE
magit-diff for color blind

### ISSUE THREAD

**Issue by ludwigpacifici** [purcell/color-theme-sanityinc-tomorrow#87]
Hello @purcell 

I enjoy very much `sanityinc-tomorrow-bright`.

Recently, the colors in the magit diff buffer changed (I suspect this [commit](https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/0c710d7294d9418edbe8c5e7c98676ceaa51a263)) and now, it is difficult for me to read it since I am color blind. Is there a way to override some colors of the theme in order to solve this unconventional issue?

**Comment by purcell** [comment]
Oh, I'm sorry to hear that. I feel like it should be possible to find colours that will work for both you and other users. Can you make any suggestions? I know this theme uses a lot of red/green to distinguish error/success, but I suspect that's not the problem in this case, since other aspects of the theme would then also be problematic for you.

**Comment by ludwigpacifici** [comment]
In general, green and red colors can be replaced by blue and orange ones. Usually, I rely more on values instead of colors to distinguish error and success. As regards diffs, `+/-` at the beginning of the line is not good enough because code indentation makes it difficult to know which line is added or removed.  

However, I do not want to push for a global change in your color theme only for one kind of light disability. That's why I asked if it is possible to override some colors from `init.el`. Otherwise, is it possible to show a different background color (in accordance with the theme) for added/removed lines?

**Comment by purcell** [comment]
:+1: A good way to override colours in a theme is to create a small "patch" theme and then load this in addition to the base theme -- `M-x customize-themes` allows you to optionally enable multiple themes simultaneously. In fact, all the usual customised variables live in a hidden `user` theme.

**Comment by ludwigpacifici** [comment]
Thank you for your suggestion. I will look how to patch it on my side.
