### ISSUE TITLE
can't seem to load it normally

### ISSUE THREAD

**Issue by gremdrus** [purcell/color-theme-sanityinc-tomorrow#90]
In my init.el I have:
```
(use-package color-theme-sanityinc-tomorrow
  :ensure t
  :config
  (load-theme 'color-theme-sanityinc-tomorrow-blue t))
```
but I get this when I try and run it:

> Error (use-package): color-theme-sanityinc-tomorrow :config: Unable to find theme file for ‘color-theme-sanityinc-tomorrow-blue’

I have to load it via M-x customize-themes and get this at the bottom of my init.el:
```
(custom-set-variables
 '(custom-enabled-themes (quote (sanityinc-tomorrow-blue)))
 '(custom-safe-themes
   (quote
    ("82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" default))))
```

How can I fix it so that the use-package version works?

**Comment by hhnr** [comment]
You should use 

```
(use-package color-theme-sanityinc-tomorrow
  :ensure t
  :config
  (load-theme 'sanityinc-tomorrow-blue t))
```
as mentioned in #86

**Comment by gremdrus** [comment]
Thank you @hhnr! That was indeed the issue.
