### ISSUE TITLE
Company-mode: selected candidate style

### ISSUE THREAD

**Issue by ddovod** [purcell/color-theme-sanityinc-tomorrow#94]
Hi there.
First, thank you very much for your work!

I use company-mode and sometimes I'm a bit confused with completion popup appearance.
Suppose we have several (more than 2) candidates:
![screenshot_2017-09-23_15-12-53](https://user-images.githubusercontent.com/9406025/30773190-32fcc53a-a074-11e7-933e-f9363a08b9d6.png)
It looks ok so we can distinguish selected item.

But if we have only 2 options, it's confusing and making me think about "what candidate is selected now? what bg color has selected candidate in general?" because current line and selected candidate have one bg color:
![screenshot_2017-09-23_15-13-40](https://user-images.githubusercontent.com/9406025/30773209-b6df2906-a074-11e7-9804-33459cfd532c.png)
![screenshot_2017-09-23_15-13-47](https://user-images.githubusercontent.com/9406025/30773210-b956e07a-a074-11e7-83e9-1fb41eaf575b.png)
(which line is selected on each of these images?)

So I think it could be great to have some one-pixel border for selected item, like this (but maybe with another color):
![screenshot_2017-09-23_15-13-47](https://user-images.githubusercontent.com/9406025/30773247-b97611d8-a075-11e7-8691-0a19e97217e0.png)
![screenshot_2017-09-23_15-13-40](https://user-images.githubusercontent.com/9406025/30773250-bdd44a10-a075-11e7-8a8f-977f21c54a39.png)

What do you think about it?
Thank you!

**Comment by purcell** [comment]
I have some of the same confusion, and I've made a change in 9c473db which I think will do the trick. Let me know if not. :-)

**Comment by ddovod** [comment]
Hi. Thank you for fast response!
Now looks much better, but inverted colors are a bit, you know, sharp or so.
![screenshot_2017-09-24_20-42-48](https://user-images.githubusercontent.com/9406025/30785070-1de48a20-a169-11e7-9c4d-f8127bce2ebc.png)

I would suggest to use box instead of inversion:
```elisp
(company-tooltip-selection (:background ,highlight :box (:line-width -1 :color ,comment)))
```
![screenshot_2017-09-24_20-45-46](https://user-images.githubusercontent.com/9406025/30785088-87e4c138-a169-11e7-9cdf-fc6b8a3c3c3c.png)

It looks more convenient in my opinion. The only issue is box consumes outer pixels no matter `:line-width` is positive or negative.
Maybe you have an idea how to fix it? I will be grateful for any help = )

**Comment by purcell** [comment]
Thanks, but I've made a conscious decision to avoid borders: text terminals can't display them, so they can't be relied on. I agree that the new display is very high contrast, which is why I avoided `inverse-video` previously... nonetheless, I've reduced the contrast a little in 059251d.
