### ISSUE TITLE
Markdown code snippets background colour

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/color-theme-sanityinc-tomorrow#97]
Hi,

first of all thanks for the great set of themes.

This is what I get  using `markdown-mode` to write a blog post.

![screen](https://user-images.githubusercontent.com/8199224/31055954-2160c10c-a6cb-11e7-847d-1e45fdcc7532.png)

As you can see, the background of `<kbd>` and code snippets makes the content hard to read.

**Comment by purcell** [comment]
Ugh! I actually fixed this just recently. Are you sure you have the latest MELPA version of this theme?

**Comment by manuel-uberti** [comment]
Yes, just re-installed to be sure.

**Comment by manuel-uberti** [comment]
Just checked: `color-theme-sanityinc-tomorrow-20170930.2008`

**Comment by manuel-uberti** [comment]
Investigating further, I forked the theme repository and tried changing those faces (setting `:background`, mainly). Nothing happens, but that's probably my poor Elisp-fu.

**Comment by drot** [comment]
You have this snippet in your config which overrides the theme:
``` 
;; Don't change font in code blocks
  (set-face-attribute 'markdown-code-face nil
                      :inherit nil
                      :background "#fb8ff133d514")
```

**Comment by purcell** [comment]
> You have this snippet in your config which overrides the theme:

Aha, that wouldn't help!

**Comment by manuel-uberti** [comment]
Thanks guys.
