### ISSUE TITLE
ClojureScript syntax faces

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/color-theme-sanityinc-tomorrow#99]
![screen](https://user-images.githubusercontent.com/8199224/31123820-e5f22ae8-a841-11e7-9821-89f12f864b26.png)

As you can see, `d3.schemeCategory20c` is not completely coloured.

Investigating a bit:

- `d3.scheme` seems to be using `font-lock-type-face`
- `Category20c` seems to be using no face at all

I was also expecting `nth` and `get` to be coloured, as it happens in the REPL:

![screen](https://user-images.githubusercontent.com/8199224/31124069-18608a0a-a843-11e7-8fb7-bd3794c713c8.png)

**Comment by purcell** [comment]
That's not a face issue, that's an issue with the mode's syntax highlighting: you'd need to contact the authors. :-)

**Comment by manuel-uberti** [comment]
Thank you, Steve, I will.
